// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eevwiajgxlogjfhinzob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVldndpYWpneGxvZ2pmaGluem9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDU4MDQsImV4cCI6MjA2OTA4MTgwNH0.RCdXNVa9OU0wzmfhflImmMOTbAj6jh0ySEHqpuhloZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
