// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkpvgmvbbvpsnqmpirek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrcHZnbXZiYnZwc25xbXBpcmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzExNTgsImV4cCI6MjA2OTM0NzE1OH0.2aeDfZgebm2e6nwxQ9dY2Ri0JBQCMzCP3O_vmXBXwoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});